version: '3'
services:
  library-db:
    container_name: library-db
    image: postgres:13.4-alpine
    environment:
      - 'POSTGRES_DB=library'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=root'
    ports:
      - '5432:5432'